server:
  port: 8080
logging:
  level:
    root: error
spring:
  application:
    name: test-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: test-service # 注册到 Nacos 的服务名。默认值为 ${spring.application.name}。